version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_DEV_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  web:
    build: .
    command: bash -c "bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
